apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: custom-argocd-rolebinding
  namespace: argocd
subjects:
- kind: User
  name: vimhask@apac.corpdir.net
  apiGroup: rbac.authorization.k8s.io/v1
roleRef:
  kind: Role
  name: custom-argocd-role
  apiGroup: rbac.authorization.k8s.io/v1